/* Devre Kasabası · bütün metinler.
   Öğretmen bu dosyayı kod bilmeden değiştirebilir: yalnızca tırnak içindeki yazıları düzenle.
   **kalın** yazmak için iki yıldız kullan. Her istasyonun görev sırası, motorun beklediği sıradır; id'leri değiştirme. */
window.PATARA_METIN = {
  dunya: {
    ad: "Patara ve Devre Kasabası",
    kisa: 'Devre Kasabası',
    tema: 'Patara Board · ilkokul ve ortaokul · iletkenlik, devre, klavye',
    soz: [
      'Şapkam yeni değil ama keşif ruhum hep yeni!',
      'Bir muz, bir kıskaç ve biraz merak. Gerisi kolay.',
      'Kıvılcım bugün çok enerjik. Hep öyle zaten.',
      'Kasabanın her köşesinde iletken bir şey saklı. Bulabilir misin?',
      'Buradaki herkes bir elektronik parça. Dokun, kendilerini anlatsınlar!',
      'Bilgisayar beni klavye sanıyor. Aramızda kalsın.',
    ],
    avAd: 'iletken avı',
    avIpucu: 'Kasabada 6 iletken nesne saklı: metal ya da kalem izi. Bulup dokun!',
    sakinIpucu: 'Kasabada 7 çeşit kasabalı yaşıyor: yürüyen LED, direnç, çip böceği, jumper kablo, buton, bazır kuşu ve USB treni. Hepsine dokun!',
  },

  tanitim: {
    baslik: 'Devre Kasabası',
    metin: [
      "Ben **Patara**. Safari şapkalı bir kaplumbağayım ama aynı zamanda bir **devre kartıyım**.",
      "**Devre Kasabası**'na hoş geldin! Burada herkes bir elektronik parça: yürüyen **LED**'ler, **dirençler**, **çip böcekleri**… Dokun, kendilerini anlatsınlar.",
      "Kasabada **yedi istasyon** var. Her birinde önce tahmin et, sonra yakından incele, görevleri bitir. Hazır mısın?",
    ],
    dugme: 'Keşfe başla',
  },

  istasyonlar: [
    {
      id: 'tanis', ad: "Patara'nın Çadırı", kisa: 'Tanış', x: 900,
      varis: 'Kasabanın girişine çadırımı kurdum. Önce beni yakından tanı!',
      gozlem: "Patara bir kaplumbağa ama aynı zamanda bir devre kartı. Kollarında altın yuvarlaklar, kabuğunda küçük ışıklar, karnında piyano tuşları var.",
      soru: 'Kollardaki altın yuvarlaklar ne işe yarar?',
      secenekler: ['Süs: parlasınlar diye', 'Ped: kıskaç takılır, her biri bir tuş olur', 'Pil yuvası: kart pille çalışır'],
      dogru: 1,
      geri: [
        'Parlak ama süs değil. Her birinin yanında bir tuş adı yazar: UP, LEFT, SPACE…',
        'Evet! Her ped bir tuş. Kıskaçla bir nesneye bağlarsan o nesne tuşa dönüşür.',
        'Patara pil kullanmaz; enerjisini USB kablosundan alır.',
      ],
      gorevler: [
        { id: 'yon', metin: 'Sol koldaki yön pedleri', yonerge: 'Sol koldaki **dört yön pedine** dokun. Her biri bir ok tuşu.',
          ipucu: ['Sol kol, ekranda senin solunda kalan kol.', 'Kolun ucundan başla: UP, LEFT, RIGHT, DOWN sırasıyla dizilir.', 'Tahtadaki ok şimdi sıradaki pedi gösteriyor.'] },
        { id: 'sag', metin: 'Sağ koldaki pedler', yonerge: 'Sağ koldaki pedlere dokun: **Space, sol tık, sağ tık, Enter**.',
          ipucu: ['Sağ kol el sallayan kol.', 'Bu kol fareyi de taklit eder: sol tık ve sağ tık burada.', 'Tahtadaki ok şimdi sıradaki pedi gösteriyor.'] },
        { id: 'gnd', metin: 'İki GND pedi', yonerge: 'Her kolun kabuğa en yakın ucunda **koyu** bir ped var: **GND**. İkisini de bul.',
          ipucu: ['GND pedleri altın değil, koyu renkli.', 'Kolun kabuğa değdiği yere bak.', 'Tahtadaki ok şimdi GND pedini gösteriyor.'] },
        { id: 'govde', metin: 'LED ekran ve piyano', yonerge: 'Kabuktaki **5×5 LED ekrana** ve karnındaki **piyanoya** dokun.',
          ipucu: ['LED ekran kabuğun ortasındaki küçük siyah kare.', 'Piyano kabuğun en altında, siyah beyaz tuşlar.', 'Tahtadaki ok şimdi yerini gösteriyor.'] },
      ],
      aciklama: "Patara'nın **10 pedi** var: 8'i tuş, 2'si **GND**. Kabuğunda **25 ışıklı LED ekran**, karnında **dokunmatik piyano**, üstünde **yön** ve **X/Y** tuşları bulunur.",
      ogretmen: 'Kartın parçalarını tanıma. Ped, GND, LED matris ve dokunmatik piyano kavramlarını adlandırır. Sınıfta gerçek kartı elden ele dolaştırıp aynı parçaları buldurun.',
    },
    {
      id: 'tak', ad: "Bilgi'nin Evi", kisa: 'Tak', x: 1900,
      varis: 'Bilgi burada yaşıyor. Onunla tanışmak için bir kablo yeter.',
      gozlem: "Bilgi eski ama becerikli bir bilgisayar. Patara'yı ona USB kablosuyla bağlayacağız.",
      soru: "Patara'yı bilgisayara taktın. Çalışması için başka ne gerekir?",
      secenekler: ['Özel bir program kurmak', 'Hiçbir şey: bilgisayar onu klavye sanır', 'İnternete bağlanmak'],
      dogru: 1,
      geri: [
        'Program gerekmez. Bilgisayarlar klavyeyi zaten tanır; Patara da kendini klavye olarak tanıtır.',
        'Doğru! Tak ve oyna. Windows, macOS, Linux ya da Chromebook fark etmez.',
        'İnternet gerekmez; Patara ile bilgisayar kabloyla doğrudan konuşur.',
      ],
      gorevler: [
        { id: 'usb', metin: 'USB kablosunu tak', yonerge: "Ortadaki siyah **USB fişini** sürükle ve Bilgi'nin **USB girişine** tak.",
          ipucu: ["USB girişi Bilgi'nin ayağında; üstünde **USB girişi** yazıyor.", 'Siyah fişe bas, basılı tutup sağa sürükle, sonra bırak.', 'Tahtadaki ok şimdi girişin yerini gösteriyor.'] },
        { id: 'yon', metin: 'Yön tuşlarına bas', yonerge: "Kartın üstündeki **dört yön tuşuna** bas ve Bilgi'nin ekranına bak.",
          ipucu: ['Yön tuşları kabuğun sol tarafında, artı şeklinde dört beyaz düğme.', 'Her birine bir kez bas: yukarı, aşağı, sol, sağ.', 'Tahtadaki ok şimdi sıradaki tuşu gösteriyor.'] },
        { id: 'xy', metin: 'X ve Y tuşları', yonerge: 'Şimdi kabuğun sağındaki **X** ve **Y** tuşlarına bas.',
          ipucu: ['Üzerinde harf yazan iki küçük düğme.', 'Biri X, biri Y. İkisine de bas.', 'Tahtadaki ok şimdi sıradaki tuşu gösteriyor.'] },
      ],
      aciklama: 'Patara bilgisayara **USB** ile bağlanır ve kendini **klavye ve fare** olarak tanıtır. Bu yüzden **sürücü ya da program gerekmez**. Bilgisayar muzu, kaşığı görmez; yalnızca **gelen tuşu** görür.',
      ogretmen: 'Tak ve çalıştır (HID) fikri. Bilgisayarın girdi aygıtlarını nasıl tanıdığını tartışın: klavye, fare, oyun kolu. Kartı farklı işletim sistemlerinde deneyin.',
    },
    {
      id: 'kiskac', ad: 'Kıskaç Atölyesi', kisa: 'Kıskaçla', x: 2900,
      varis: 'Timsah Kıskaç işbaşında. Kıskaçlar olmadan hiçbir şey bağlanmaz!',
      gozlem: "Tezgâhta dört kırmızı kıskaç var; her biri Patara'nın bir pedinden çıkıyor. Masada muz, elma, oyun hamuru ve kaşık bekliyor.",
      soru: 'Kıskacın bir ucu pede takılı. Öbür ucunu nereye takarız?',
      secenekler: ['Bilgisayara', 'İletken bir nesneye: muz, kaşık, hamur…', 'Duvardaki prize'],
      dogru: 1,
      geri: [
        'Bilgisayar zaten USB ile bağlı. Kıskaçlar nesnelere gider.',
        'Evet! Kıskaç nesneyi pede bağlar; o nesne artık bir tuş.',
        'Asla! Priz tehlikelidir. Patara çok küçük ve güvenli bir akımla çalışır; prize hiçbir şey takılmaz.',
      ],
      gorevler: [
        { id: 'ilk', metin: 'İlk kıskaç: muz', yonerge: '**UP** pedinden çıkan kıskacın **başını** sürükle ve **muza** ısırt.',
          ipucu: ['UP pedi sol kolun en ucunda.', 'Kıskacın gümüş başına bas ve muzun üstüne sürükle.', 'Tahtadaki ok şimdi kıskacı ve muzu gösteriyor.'] },
        { id: 'hepsi', metin: 'Kalan üç kıskaç', yonerge: 'Kalan üç kıskacı **elmaya, hamura ve kaşığa** bağla. Hangi kıskaç hangisine, sen seç.',
          ipucu: ['Her nesneye bir kıskaç yeter.', 'Bağlanmamış kıskacın başını boştaki bir nesneye sürükle.', 'Tahtadaki ok şimdi sıradaki kıskacı gösteriyor.'] },
        { id: 'oku', metin: 'Hangi tuş?', yonerge: 'Bağlantılara bak: aşağıda sorulan nesneye dokununca **hangi tuş** basılır? Seç.',
          ipucu: ['Nesneden çıkan kabloyu takip et.', 'Kablonun bağlı olduğu pedin adı tuşun adıdır.', 'Tahtadaki ok şimdi o kablonun pedini gösteriyor.'] },
      ],
      aciklama: 'Her **kıskaç** bir pedi bir nesneye bağlar. Muz UP pedine bağlıysa muza dokunmak **↑ tuşuna basmak** demektir. Bağlantıyı değiştirirsen tuş da değişir.',
      ogretmen: 'Girdi eşleme. Öğrenciler aynı nesneyi farklı pedlere bağlayıp sonucun nasıl değiştiğini tahmin etsin. Güvenlik: kıskaçlar yalnızca karta ve nesnelere takılır; priz ve pil asla.',
    },
    {
      id: 'halka', ad: 'Halka Meydanı', kisa: 'Halka', x: 3900,
      varis: 'Meydandaki bakır halkayı görüyor musun? Deniz de burada. Bir halka kuracağız ama önce bir şey eksik…',
      gozlem: "Muz UP pedine bağlı. Deniz muza dokunmaya hazır. Siyah GND kıskacı ise yerde duruyor.",
      soru: 'GND kıskacı yerdeyken Deniz muza dokunursa ne olur?',
      secenekler: ['Yine ↑ tuşu basılır', 'Hiçbir tuş basılmaz', 'Muz ısınır'],
      dogru: 1,
      geri: [
        "Kıvılcım muzdan Deniz'e geçer ama eve dönemez. Halka açıksa tuş basılmaz.",
        'Güzel tahmin! Şimdi deneyip görelim.',
        'Akım çok çok küçük; muz ısınmaz, Deniz hiçbir şey hissetmez.',
      ],
      gorevler: [
        { id: 'acik', metin: 'GND olmadan dene', yonerge: "GND kıskacı yerde. **Muza dokun** ve Kıvılcım'ın nerede takıldığını izle.",
          ipucu: ['Muza ya da Deniz\'in eline dokunabilirsin.', 'Kıvılcım UP pedinden çıkıp kablodan muza gider.', 'Tahtadaki ok şimdi muzu gösteriyor.'] },
        { id: 'gnd', metin: 'GND kıskacını ver', yonerge: "Yerdeki siyah **GND kıskacını** sürükle ve **Deniz'in boştaki eline** ver.",
          ipucu: ['Siyah kıskaç Deniz\'in ayaklarının yanında.', 'Kıskacı sürükle, Deniz\'in sol eline bırak.', 'Tahtadaki ok şimdi Deniz\'in elini gösteriyor.'] },
        { id: 'kapali', metin: 'Halkayı kapat', yonerge: 'Şimdi tekrar **muza dokun**. Halka kapanacak mı?',
          ipucu: ['GND artık Deniz\'in elinde.', 'Muza dokun ve Kıvılcım\'ı sonuna kadar izle.', 'Tahtadaki ok şimdi muzu gösteriyor.'] },
        { id: 'zincir', metin: 'Arkadaş zinciri', yonerge: "Ada ve Can geldi; üçü el ele bir **zincir** kurdu ama **bir yerde eller ayrık**. Boşluğa dokunup elleri birleştir, sonra **muza dokun**.",
          ipucu: ['Eli havada kalan iki çocuğu bul.', 'Boşluk Can ile Ada\'nın arasında. Oraya dokun, sonra muza.', 'Tahtadaki ok şimdi sıradaki yeri gösteriyor.'] },
      ],
      aciklama: "Akım bir **halka** ister: pedden nesneye, nesneden **sana**, senden **GND**'ye ve karta geri. Sen de halkanın bir parçasısın! GND kıskacı elinde değilse halka **açık** kalır ve tuş basılmaz. El ele tutuşan bir **zincir** de halkaya katılır; biri elini bırakırsa halka açılır.",
      ogretmen: 'Kapalı ve açık devre. Öğrenciler el ele tutuşup bir insan zinciri kursun: zincirin bir ucu GND, öbür ucu nesneye dokunur. Zincir kopunca tuş basılmaz.',
    },
    {
      id: 'iletken', ad: 'Malzeme Pazarı', kisa: 'İletken mi?', x: 4900,
      varis: "Silgi ve İletken Dostlar burada tartışıyor: kim Kıvılcım'ı geçirir?",
      gozlem: 'Tezgâhta sekiz nesne var. Bazıları Kıvılcım\'ı geçirir, bazıları geçirmez. Test kıskaçlarıyla deneyebilirsin.',
      soru: "Kurşun kalemle çizilmiş koyu bir çizgi Kıvılcım'ı geçirir mi?",
      secenekler: ['Hayır, kâğıt geçirmez', 'Evet, kalem izi iletir', 'Yalnızca kırmızı kalemle'],
      dogru: 1,
      geri: [
        'Kâğıt tek başına geçirmez ama üstündeki koyu kurşun kalem izi (grafit) geçirir!',
        'Evet! Kurşun kalemin içi grafittir ve iletir. Kâğıda çizdiğin yol bir tuşa dönüşebilir.',
        'Rengi değil, içindeki grafit önemli. Boya kalemleri iletmez.',
      ],
      gorevler: [
        { id: 'test', metin: 'Bir nesneyi test et', yonerge: 'Bir nesneyi sürükle ve **test kıskaçlarının arasına** bırak. Lamba yanacak mı?',
          ipucu: ['Test yeri, iki kıskacın ortasındaki kesik çizgili daire.', 'Herhangi bir nesneyi sürükleyip oraya bırak.', 'Tahtadaki ok şimdi bir nesneyi ve test yerini gösteriyor.'] },
        { id: 'ayir', metin: 'Sekiz nesneyi ayır', yonerge: "Nesneleri doğru sepete sürükle: **Kıvılcım'ın sepeti** iletken, **Silgi'nin sepeti** yalıtkan.",
          ipucu: ['Emin değilsen önce test yerinde dene.', 'Metal ve su içeren şeyler iletir; plastik, lastik, tahta, kâğıt, cam iletmez.', 'Tahtadaki ok şimdi sıradaki nesnenin sepetini gösteriyor.'] },
        { id: 'neden', metin: 'Ortak özellik', yonerge: 'Son soru: iletken nesnelerin çoğunda **ortak** olan ne? Aşağıdan seç.',
          ipucu: ['Kaşık, para, anahtar… bir de meyveler ve hamur.', 'Biri metal, öbürü içinde su olan şeyler.', 'Doğru cevap: metal ya da su içerirler.'] },
      ],
      aciklama: "**İletkenler** Kıvılcım'ı geçirir: metaller (kaşık, para, anahtar, folyo), su içeren şeyler (meyve, hamur) ve kurşun kalem izi. **Yalıtkanlar** geçirmez: plastik, lastik, tahta, kâğıt, cam. Patara'ya yalnızca iletkenleri bağlarız.",
      ogretmen: 'İletken ve yalıtkan maddeler (Fen: elektrik ünitesi). Sınıfta gerçek kartla nesne kutusu hazırlayın; önce tahmin tablosu doldurulsun, sonra test edilsin.',
    },
    {
      id: 'sahne', ad: 'Işık Sahnesi', kisa: 'Işık ve müzik', x: 5900,
      varis: 'Sahne bizim! Işıklar ve müzik kabuğumda.',
      gozlem: "Patara'nın kabuğunda 25 küçük ışık, karnında 8 piyano tuşu var. Piyano için kıskaç gerekmez.",
      soru: 'Piyano tuşları neden kablo istemez?',
      secenekler: ['Dokunmayı kendileri hisseder (dokunmatik)', 'İçlerinde pil var', 'Sesle çalışırlar'],
      dogru: 0,
      geri: [
        'Evet! Tuşlar parmağının dokunuşunu hisseder; telefon ekranı gibi.',
        'Pil yok; tuşlar dokunmayı hisseden yüzeylerdir.',
        'Ses çıkarırlar ama sesle çalışmazlar; dokunuşu hissederler.',
      ],
      gorevler: [
        { id: 'ciz', metin: 'Resmi kopyala', yonerge: 'LED ekrandaki ışıklara dokunarak **örnekteki resmi** kopyala.',
          ipucu: ['Her ışığa dokununca yanar ya da söner.', 'Satır satır git: önce üst sıra.', 'Tahtadaki ok şimdi değişmesi gereken ışığı gösteriyor.'] },
        { id: 'melodi', metin: 'Melodiyi tekrarla', yonerge: 'Önce **Dinle** düğmesine bas. Sonra piyanoda **aynı tuşlara** sırayla bas.',
          ipucu: ['Patara çalarken yanan tuşları izle.', 'Unutursan Dinle düğmesine yeniden bas.', 'Tahtadaki ok şimdi sıradaki tuşu gösteriyor.'] },
        { id: 'serbest', metin: 'Kendi resmin', yonerge: 'Şimdi kendi resmini çiz: en az **8 ışık** yak, sonra **Göster** düğmesine bas.',
          ipucu: ['Bir harf, bir yüz ya da bir ok çizebilirsin.', 'Yanan ışıkları say: en az 8 olsun.', 'Tahtadaki ok şimdi sönük bir ışığı gösteriyor.'] },
      ],
      aciklama: '**5×5 LED** ekran 25 ışıktan oluşur; oklar, yüzler, kalpler çizebilirsin. **Dokunmatik piyano** parmağının dokunuşunu hisseder; kıskaç ve GND gerekmez.',
      ogretmen: 'Çıktı aygıtları ve piksel fikri. 5×5 ızgarada harf tasarlatın; ortaokulda ızgarayı 0 ve 1 dizisiyle (ikilik) yazdırın.',
    },
    {
      id: 'oyun', ad: 'Oyun Salonu', kisa: 'Oyun zamanı', x: 6900,
      varis: 'Son durak! Mutfak kumandasıyla oyun zamanı.',
      gozlem: 'Muz ↑, elma ←, hamur →, kaşık ↓ pedine bağlı. Bu dört nesne artık bir oyun kumandası.',
      soru: 'Muzla oynarken bilgisayar ne görür?',
      secenekler: ['Bir muz', 'Yalnızca ↑ tuşunu', "Deniz'in parmağını"],
      dogru: 1,
      geri: [
        'Bilgisayarın gözü yok! Yalnızca Patara\'dan gelen tuşu görür.',
        'Doğru! Bilgisayar için muza dokunmak ile ↑ tuşuna basmak aynı şey.',
        'Parmağı Patara hisseder, bilgisayar değil. Bilgisayar yalnızca ↑ tuşunu görür.',
      ],
      gorevler: [
        { id: 'ilk', metin: 'İlk hamle', yonerge: '**Muza** dokun: Patara yukarı gitsin.',
          ipucu: ['Muz, kumandanın üstündeki nesne.', 'Muz ↑ tuşuna bağlı.', 'Tahtadaki ok şimdi muzu gösteriyor.'] },
        { id: 'yildiz', metin: 'Yıldıza ulaş', yonerge: "Dört nesneyi kullanarak Patara'yı **yıldıza** götür. Taşlardan geçemezsin.",
          ipucu: ['Önce yolu gözünle izle, sonra hamle yap.', 'Elma sola, hamur sağa, kaşık aşağı götürür.', 'Tahtadaki ok şimdi sıradaki hamleyi gösteriyor.'] },
        { id: 'klavye', metin: 'Klavyeyle dene', yonerge: '**Klavyenin ok tuşlarıyla** bir hamle yap (ekrandaki küçük klavye de olur). Bilgi için fark var mı?',
          ipucu: ['Bilgisayarındaki ok tuşları ya da tahtadaki küçük klavye.', 'Herhangi bir ok tuşu yeter.', 'Tahtadaki ok şimdi küçük klavyeyi gösteriyor.'] },
      ],
      aciklama: 'Bilgisayar için **muza dokunmak** ile **↑ tuşuna basmak** aynı şeydir. Patara nesneleri **tuşa çevirir**; klavyeyle çalışan her oyun, Scratch projesi ya da sunum muzla da çalışır.',
      ogretmen: 'Girdi ve çıktı, algoritma. Scratch ile ok tuşlarına tepki veren basit bir labirent oyunu yazdırın; sonra kartla meyve kumandası yapın. Ortaokulda en kısa yolu önceden planlatın.',
    },
  ],

  /* kasabalılar: dokununca söyledikleri (her dokunuşta sıradaki söz) */
  sakinler: {
    led: { ad: 'LED', soz: ['Ben LED! Uzun bacağım artı (+), kısa bacağım eksi (−).', 'Akım beni doğru yönden geçerse yanarım. Ters takarsan küserim!', "Patara'nın kabuğunda benden 25 tane var."] },
    direnc: { ad: 'Direnç', soz: ['Ben direnç: akımı yavaşlatırım. LED\'ler beni çok sever.', 'Renkli şeritlerim değerimi söyler: kahverengi, siyah, kırmızı = 1000 ohm.'] },
    cip: { ad: 'Çip böceği', soz: ["Ben bir mikroçip: minicik bir beyin. Patara'nın içinde de bir çip var!", 'Bacaklarım aslında pin: her biri bir bağlantı.'] },
    jumper: { ad: 'Jumper kablo', soz: ["Jumper kablo! Breadboard'a ve Patara'nın pinlerine takılırım.", 'Kıskaçtan sonra sıra bende: daha ince işler için.'] },
    buton: { ad: 'Buton', soz: ['Bas, bırak: tık! Ben bir butonum.', "Patara'nın yön tuşları da benim gibi butondur."] },
    bip: { ad: 'Bazır kuşu', soz: ['Bip! Ben bir bazır (buzzer): elektrikle ses çıkarırım.', 'Bip bip! Saatlerde, oyuncaklarda, fırınlarda ben öterim.'] },
    tren: { ad: 'USB treni', soz: ["USB treni! Patara'dan Bilgi'ye tuş taşırım: ↑, SPACE, ENTER…", 'Kablo benim rayım. Bir ucu Patara, öbür ucu Bilgi.'] },
  },

  /* iletken avı: dünyaya saklanmış nesneler (x: dünya konumu, y: yerden yükseklik) */
  avlar: [
    { id: 'para', ad: 'Madeni para', x: 640, y: 596, not: 'Metal: iletken!' },
    { id: 'anahtar', ad: 'Anahtar', x: 2160, y: 470, not: 'Metal anahtar: iletken!' },
    { id: 'atas', ad: 'Ataş', x: 3150, y: 498, not: 'Metal tel: iletken!' },
    { id: 'folyo', ad: 'Alüminyum folyo', x: 4130, y: 592, not: 'Folyo ince bir metaldir: iletken!' },
    { id: 'kalem', ad: 'Kurşun kalem', x: 5640, y: 596, not: 'İçindeki grafit iletir: iletken!' },
    { id: 'kasik', ad: 'Kaşık', x: 6620, y: 596, not: 'Metal kaşık: iletken!' },
  ],

  ogretmenGenel: "Devre Kasabası, Patara Board'u ilk kez kullanacak 7–14 yaş öğrenciler için hazırlandı. Kasabalılar (LED, direnç, çip, jumper kablo, buton, bazır, USB treni) dokununca kendilerini tanıtır; elektronik parçalara ilk merakı uyandırır. Her istasyon tahminle açılır, yakın planda 2–4 görevle sürer, kısa bir açıklamayla kapanır. Tek başına ya da akıllı tahtada sınıfça oynanabilir. İlerleme tarayıcıda saklanır; menüdeki Sıfırla düğmesiyle silinir. Metinler js/metinler.js dosyasındadır.",
};
